// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfpEQ4v7ynMjlqqG-npeyQlBMM2YFprc',
    appId: '1:592369729548:ios:c18fa3f650306a30636e29',
    messagingSenderId: '592369729548',
    projectId: 'wattwais',
    storageBucket: 'wattwais.firebasestorage.app',
    iosBundleId: 'com.example.wattwais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqfpEQ4v7ynMjlqqG-npeyQlBMM2YFprc',
    appId: '1:592369729548:ios:c18fa3f650306a30636e29',
    messagingSenderId: '592369729548',
    projectId: 'wattwais',
    storageBucket: 'wattwais.firebasestorage.app',
    iosBundleId: 'com.example.wattwais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYqzR1bjtxWgkgoaDL40RozApIifHlxvM',
    appId: '1:592369729548:web:da2890d930ef60ea636e29',
    messagingSenderId: '592369729548',
    projectId: 'wattwais',
    authDomain: 'wattwais.firebaseapp.com',
    storageBucket: 'wattwais.firebasestorage.app',
    measurementId: 'G-CE96M6Y9KC',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYqzR1bjtxWgkgoaDL40RozApIifHlxvM',
    appId: '1:592369729548:web:da2890d930ef60ea636e29',
    messagingSenderId: '592369729548',
    projectId: 'wattwais',
    authDomain: 'wattwais.firebaseapp.com',
    storageBucket: 'wattwais.firebasestorage.app',
    measurementId: 'G-CE96M6Y9KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqnTHa_aExAkiZlT8gIkU5G-FJjYLtCuU',
    appId: '1:592369729548:android:981e4df31c320149636e29',
    messagingSenderId: '592369729548',
    projectId: 'wattwais',
    storageBucket: 'wattwais.firebasestorage.app',
  );

}